#!/bin/bash

set -e

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

CARGO=${CARGO:-cargo}

function is_stable {
  (rustc --version | grep -q "rustc 1.29" && echo "yes") || echo "no"
}

if [ "x$(is_stable)" == "xno" ] ; then
  echo -e "${GREEN}Skip, there isn't stable${NC}"
  exit 0
fi

rustfmt --version > /dev/null 2>&1 || (
  echo -e "${GREEN}rustup component add clippy-preview${NC}"
  rustup component add clippy-preview
  echo
)

echo -e "${GREEN}${CARGO} clippy --version${NC}"
${CARGO} clippy --version
echo

echo -e "${GREEN}${CARGO} clippy${NC}"
${CARGO} clippy

echo -e "${YELLOW}OK${NC}"
